### ISSUE TITLE
Appears to be failing to work on 1.20.6

### ISSUE THREAD

**Issue by Thecat8413** [sammko/servertick-fabric#12]
Unfortunately it looks like servertick is no longer working. I tried to spin up a 1.20.2 instance to test and it looks like it still isn't working. I'm guessing an update to fabric broke it. 

Tested on:
Minecraft: 1.20.2, 1.20.4, 1.20.6 
Fabric: 0.15.11

**Comment by sammko** [comment]
Hey, vanilla can do this from some (not sure which) version, so in 1.20.6 you don't need servertick anymore. Just try enabling the F3 TPS graph on a server and it should just work if you're op. I should archive this repo

**Comment by Thecat8413** [comment]
Ahh! Makes sense. Thank you for info.
