### ISSUE TITLE
Suggestion: Bukkit server plugin

### ISSUE THREAD

**Issue by Gaming32** [sammko/servertick-fabric#4]
My suggestion is for a Bukkit plugin that implements the server-side of this plugin. This would allow the features of this mod to be usable on a Spigot (or Paper) server. It would still require the mod installed client-side, though.
This would require that the client version of the mods also supports a protocol plugin ([wiki.vg](https://wiki.vg/Plugin_channels), [dinnerbone.com](https://dinnerbone.com/blog/2012/01/13/minecraft-plugin-channels-messaging/)) form of data transfer.

**Comment by sammko** [comment]
Hi, thanks for the suggestion. Good news, It's already done: https://github.com/sammko/servertick-paper. I'm not actively maintaining it though and I don't upload the builds anywhere, however it should build without any issues and should probably work under newer Paper versions. Do let me know if you run into any issues.

**Comment by sammko** [comment]
Turns out there is a build: https://github.com/sammko/servertick-paper/releases/tag/v1.1

**Comment by Gaming32** [comment]
Thanks :)

**Comment by Gaming32** [comment]
This plugin also definitely works on Spigot too. You don't need Paper.
EDIT: Nope, I'm wrong.

**Comment by Felix14-v2** [comment]
> Good news, It's already done: https://github.com/sammko/servertick-paper

Maybe also add it to the Modrinth page?
