### ISSUE TITLE
Add 1.18.2 version tag to modrinth download

### ISSUE THREAD

**Issue by ghost** [sammko/servertick-fabric#6]
Hello,

First of all I would like to thank you for this amazing mod. It helps me a lot checking my servers performance and is simply the best way to integrate the servers TPS into a client. 

I've tried switching to a CLI Mod Manager (Ferium) today and found it impossible to add Servertick to a Minecraft 1.18.2 profile because the Modrinth version is only tagged as compatible with 1.18. Because it doesn't seem like Ferium will add the ability to pick a specific mod version very soon, I would like to ask you if you could quickly tag the Modrinth version as 1.18.2 compatible. I've already used it extensively on my 1.18.2 Server and had no problems at all.

Thank you very much!

**Comment by sammko** [comment]
Thanks for the heads-up, I've added the missing tags. Glad you like the mod!
