### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by Avakining** [sammko/servertick-fabric#9]
Currently, servertick crashes on 1.20.2. When you get a chance, please update. Thanks!

**Comment by sammko** [comment]
Hopefully done in v1.9! Let me know if you run into any issues.

**Comment by Felix14-v2** [comment]
RIP Server Tick 🥲
![image](https://github.com/sammko/servertick-fabric/assets/75726196/2977376c-a5db-4076-a354-3fa21c67a710)
At least now you're build into the game.
